# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7350eaf1cb30606bab1bb3958fa0db9d490a7222cc92751e73c1b6ee2337003663cd4e3334c784f34eac6a34651693a4bc0da61d62e1d4712ebf472d238e3ae7

test:
  secret_key_base: feacfdc57ce49ce0068f4f7fc0f83faaac628db04d0a9e6e411a4af0436cfc5ad9e5c0cc4c0d577c12e4844a19166f1ccb83aff59c0efcc18771fb27beb9deb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
